version: "3.8"
services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: application
    container_name: rag_bot
    ports:
      - 8080:5000
    volumes:
      - appdata:/app/doc_chat/data
    networks:
      - net
    env_file:
      - .env

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    volumes:
      - index_data:/chroma/chroma
    ports:
      - 8000:8000
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local
  appdata:
    driver: local

networks:
  net:
    driver: bridge